name: MinecraftToMatrix
version: 1.0
main: io.papermc.testplugin.MinecraftToMatrix
description: Bridges Minecraft messages to a Matrix room
author: Scott Bronson
website: https://github.com/bronson/minecraft-to-matrix
api-version: '1.21'