name: MinecraftToMatrix
version: 0.1
main: io.papermc.testplugin.MinecraftToMatrix
description: Bridges Minecraft messages to a Matrix room
author: Scott Bronson
website: https://github.com/bronson/minecraft-to-matrix
api-version: '1.21.5'

commands:
  command:
    description: "This is a command"
    usage: "/matrix <arg>"
    aliases: [cmd, command]
    permission: permission.node
    permission-message: "You do not have permission to use this command"
